# Generated by Django 4.0.2 on 2022-04-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="category",
            field=models.ManyToManyField(to="rewards.Category"),
        ),
    ]
