# Generated by Django 4.0.2 on 2022-04-03 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recycle", "0002_create_calculate_distance_function"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rewards", "0002_alter_image_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="caption",
        ),
        migrations.RemoveField(
            model_name="image",
            name="category",
        ),
        migrations.RemoveField(
            model_name="image",
            name="consent",
        ),
        migrations.RemoveField(
            model_name="image",
            name="event_type",
        ),
        migrations.RemoveField(
            model_name="image",
            name="location",
        ),
        migrations.RemoveField(
            model_name="image",
            name="user",
        ),
        migrations.CreateModel(
            name="ImageMeta",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("caption", models.CharField(max_length=150, null=True)),
                ("consent", models.BooleanField(default=False)),
                ("category", models.ManyToManyField(to="rewards.Category")),
                (
                    "event_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rewards.event"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recycle.zipcode",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
