# Generated by Django 4.0.2 on 2022-04-03 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0003_remove_image_caption_remove_image_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="meta",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="rewards.imagemeta"
            ),
            preserve_default=False,
        ),
    ]
