# Generated by Django 4.0.2 on 2022-04-15 23:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0004_image_meta"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="approved",
        ),
        migrations.RemoveField(
            model_name="image",
            name="uploaded_on",
        ),
        migrations.AddField(
            model_name="imagemeta",
            name="approved",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="imagemeta",
            name="uploaded_on",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
