# Generated by Django 4.0.2 on 2022-04-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0005_remove_image_approved_remove_image_uploaded_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagemeta",
            name="approved",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
