# Generated by Django 4.0.2 on 2022-04-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0007_creditslookup_earngreencredits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earngreencredits',
            name='object_id',
            field=models.PositiveIntegerField(auto_created=True),
        ),
    ]
