# Generated by Django 4.0.2 on 2022-04-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rewards", "0008_alter_earngreencredits_object_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="earngreencredits",
            name="object_id",
            field=models.PositiveIntegerField(auto_created=True, null=True),
        ),
    ]
