# Generated by Django 4.0.2 on 2022-04-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0009_alter_earngreencredits_object_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earngreencredits',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
