# Generated by Django 4.0.2 on 2022-03-26 02:34

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reuse", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="search_token",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
