# Generated by Django 4.0.2 on 2022-03-13 22:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reuse", "0003_alter_post_created_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="url",
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 3, 13, 18, 45, 42, 922390)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
