# Generated by Django 4.0.2 on 2022-03-13 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reuse", "0004_alter_image_url_alter_post_created_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_on",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 3, 13, 18, 46, 16, 958175)
            ),
        ),
    ]
