# Generated by Django 4.0.2 on 2022-03-26 03:01

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reuse', '0004_search_vector_trigger'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='reuse_post_search__e3838d_gin'),
        ),
    ]
