# Generated by Django 4.0.2 on 2022-03-30 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reuse", "0003_rename_street_address_ngolocation_address_and_more"),
        ("reuse", "0005_post_reuse_post_search__e3838d_gin"),
    ]

    operations = []
