# Generated by Django 4.0.1 on 2022-04-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reuse", "0007_post_updated_on_alter_post_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="approved",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
        migrations.AlterField(
            model_name="post",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
