# Generated by Django 4.0.2 on 2022-05-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reuse", "0010_postconcernlogs"),
    ]

    operations = [
        migrations.AddField(
            model_name="postconcernlogs",
            name="message",
            field=models.TextField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
