# Generated by Django 4.0.2 on 2022-05-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reuse", "0011_postconcernlogs_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postconcernlogs",
            name="message",
            field=models.TextField(max_length=500, null=True),
        ),
    ]
