# Generated by Django 4.0.2 on 2022-05-05 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reuse", "0012_alter_postconcernlogs_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="postconcernlogs",
            name="checked",
            field=models.BooleanField(default=False),
        ),
    ]
