# Generated by Django 4.0.2 on 2022-03-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                null=True, upload_to="Avatars", verbose_name="Avatar"
            ),
        ),
    ]
