# Generated by Django 4.0.1 on 2022-05-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_volunteerapplication_delete_volunteersapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteerapplication",
            name="admin",
            field=models.BooleanField(default=False),
        ),
    ]
