# Generated by Django 4.0.2 on 2022-05-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_volunteerapplication_delete_volunteersapplication"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("question_type", models.IntegerField(choices=[(1, "Image"), (2, "Text")])),
                (
                    "answer",
                    models.IntegerField(choices=[(None, "(Unknown)"), (0, "No"), (1, "Yes")]),
                ),
                ("image", models.URLField(max_length=3000, null=True)),
                ("question", models.TextField()),
                ("text", models.TextField(null=True)),
            ],
        ),
    ]
