# Generated by Django 4.0.2 on 2022-03-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_avatar_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='Avatars'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
