# Generated by Django 4.0.1 on 2022-05-08 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_volunteerapplication_admin"),
    ]

    operations = [
        migrations.RenameField(
            model_name="volunteerapplication",
            old_name="admin",
            new_name="approved",
        ),
    ]
