# Generated by Django 4.0.2 on 2022-05-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="image",
            field=models.URLField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
