# Generated by Django 4.0.2 on 2022-05-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_question_image_alter_question_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer",
            field=models.IntegerField(choices=[(None, "(Unknown)"), (0, "Approve"), (1, "Deny")]),
        ),
    ]
