# Generated by Django 4.0.2 on 2022-05-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_question_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer",
            field=models.IntegerField(choices=[(0, "Approve"), (1, "Deny")]),
        ),
    ]
