# Generated by Django 4.0.2 on 2022-05-07 23:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_question_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteerapplication",
            name="score",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(0),
                ],
            ),
        ),
    ]
