# Generated by Django 4.0.1 on 2022-05-10 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_rename_admin_volunteerapplication_approved"),
        ("accounts", "0009_alter_volunteerapplication_approved_by"),
    ]

    operations = []
