# Generated by Django 4.0.2 on 2022-03-15 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='zipcode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recycle.zipcode', verbose_name='Zipcode'),
        ),
    ]
