# Generated by Django 4.0.1 on 2022-04-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteerlogs",
            name="reason",
            field=models.CharField(default="None", max_length=250),
        ),
    ]
