# Generated by Django 4.0.1 on 2022-04-25 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moderation", "0003_volunteerlogs_approved_volunteerlogs_approved_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteerlogs",
            name="approved",
            field=models.CharField(default="False", max_length=10),
        ),
    ]
