# Generated by Django 4.0.2 on 2022-04-01 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recycle", "0002_create_calculate_distance_function"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetailerLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("phone", models.CharField(max_length=17, null=True)),
                ("name", models.CharField(max_length=250)),
                ("address", models.TextField()),
                ("type", models.CharField(max_length=250)),
                (
                    "zip_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recycle.zipcode",
                    ),
                ),
            ],
        ),
    ]
