# Generated by Django 4.0.2 on 2022-02-27 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DropOffLocations',
            new_name='DropOffLocation',
        ),
        migrations.RenameModel(
            old_name='ZipCodes',
            new_name='ZipCode',
        ),
    ]
